### PR TITLE
Vacuum sensing 100hz signal fix

### PR DESCRIPTION
**Pull request by brainstorm**
Remove the 100Hz signal on the SS2/PB3 pin of the ATxmega TinyG MCU.

This PR is dependant on PR #1 .

### CODE REVIEW

**Comment by ian-arkver** [comment]
The last commit (ad38088) does not do what the comment and commit message claim it does.

The DIR register is a bitfield with one bit per pin. If a bit is '1' the pin is an output.

The effect of the statement is to clear bits 0 and 1 while leaving all the other bits unchanged.

**Comment by ian-arkver** [comment]
I'm not sure why configuring the ADC to differential input using PORTB.0 as the low input would make things *more* stable. This pin is the BOOT jumper. Is this jumper normally fitted to tie this pin to ground?

**Comment by brainstorm** [comment]
There's an insane amount of nuance in Atmel ADC configurations and TinyG, hang in there, we are going deep in the rabbit hole and troubleshooting this, [check this out if you are interested](https://blog.frankvh.com/2010/01/03/atmel-xmega-adc-problems-solutions/) ;)

For instance, there's another gotcha Anthony found out today:

Screenshot 2023-02-24 at 10 10 29 pm

That [2Mhz signal issue from yesterday](https://github.com/markmaker/TinyG/pull/3#issuecomment-1440962921)? Gone today after removing the capacitor.

Unfortunately our sensor stops responding as soon as it's connected to the TinyG, so we do know it's a software configuration detail, but we are trying a bunch of things and commit messages might not reflect exactly what we are actually doing (i.e we were discussing about making sure that PB3 is NOT an output, I might have gotten distracted when writing the commit message and discussing the topic with the others), sorry ;)

**Comment by brainstorm** [comment]
After reflashing the "stock" firmware from Mark with ADC and the 100Hz signal and fine tuning the cap and resistor the vacuum sensing works fine, closing.

**Pull request closed without merging**
